### ISSUE TITLE
NoSuchMethodError: org.springframework.boot.builder.SpringApplicationBuilder.<init>

### ISSUE THREAD

**Issue by naliniranjan82** [spring-cloud/spring-cloud-config#836]
i am  using spring-boot-starter-parent version 2.0.0.M2 version but when i try run application i got below error..

java.lang.NoSuchMethodError: org.springframework.boot.builder.SpringApplicationBuilder.<init>([Ljava/lang/Object;)V
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:120)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:84)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:62)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:122)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:72)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:328)

**Comment by ryanjbaxter** [comment]
What version of Spring Cloud?

**Comment by domi55** [comment]
hi @ryanjbaxter 
In my case for Spring Cloud I use:

    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-netflix</artifactId>
      <version>2.0.0.M2</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>

    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-archaius</artifactId>
     </dependency>

And for Spring Boot

    <dependency>                
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-dependencies</artifactId>
      <version>2.0.0.M3</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>

According to https://projects.spring.io/spring-cloud/ this combination (Spring Boot 2.0.0.M3 and Spring Cloud Netflix 2.0.0.M2) should work right?

**Comment by spencergibb** [comment]
Boot M5 and Finchley. M3 are the latest versions that work today, can you try with those?

**Comment by domi55** [comment]
Hm. How am I supposed to use Archaius with Finchley.M3? According to http://repo.spring.io/milestone/org/springframework/cloud/spring-cloud-starter-archaius/ the last Milestone Release of spring-cloud-starter-archaius was back in August. And explicitly specifying `<version>2.0.0.M2</version>`gave me the same exception:
```
15:17:20.947 [main] ERROR org.springframework.boot.SpringApplication - Application startup failed
java.lang.NoSuchMethodError: org.springframework.boot.builder.SpringApplicationBuilder.<init>([Ljava/lang/Object;)V
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:157)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:98)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:64)
```

**Comment by spencergibb** [comment]
I don't see how Archaius has anything to do with it. Besides, we renamed the starters http://repo.spring.io/milestone/org/springframework/cloud/spring-cloud-starter-netflix-archaius/

Can you tell me why you aren't using the `spring-cloud-dependencies` BOM?

**Comment by domi55** [comment]
Thanks @spencergibb. I terms of declaring the dependencies it works now. I have:
```
<dependency>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-dependencies</artifactId>
  <version>2.0.0.M5</version>
  <type>pom</type>
  <scope>import</scope>
</dependency>
```
```
<dependency>
  <groupId>org.springframework.cloud</groupId>
  <artifactId>spring-cloud-dependencies</artifactId>
  <version>Finchley.M3</version>
  <type>pom</type>
  <scope>import</scope>
</dependency>
```
```
<dependency>
  <groupId>org.springframework.cloud</groupId>
  <artifactId>spring-cloud-starter-netflix-archaius</artifactId>
</dependency>
```
Still gives me:
```
15:28:32.158 [main] ERROR org.springframework.boot.SpringApplication - Application startup failed
java.lang.NoSuchMethodError: org.springframework.boot.builder.SpringApplicationBuilder.<init>([Ljava/lang/Object;)V
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:157)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:98)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:64)
```

**Comment by spencergibb** [comment]
I created a project from start.spring.io with those dependencies and I don't get that error. My guess is you still have mixed up dependencies. If you can provide a project that recreates the problem, feel free to reopen.

**Comment by domi55** [comment]
Alright. Thanks for your help. Let me check double-check my dependencies.

**Comment by spencergibb** [comment]
NP! I'll be happy to look again.

**Comment by CluEleSsUK** [comment]
I have the same issue as OP.  I've noticed that the `BootstrapApplicationListener` for the spring-cloud-context 1.3.3.RELEASE uses an empty constructor for `SpringApplicationBuilder` at line 161, but  the 2.0.0.RELEASE of spring boot has only the following constructor: 
```	
public SpringApplicationBuilder(Class<?>... sources) 
```

**Comment by spencergibb** [comment]
Not related. Spring cloud 1.x (Edgware and earlier) is not compatible with boot 2

**Comment by eepstein** [comment]
@spencergibb care to share your configuration somewhere as an example / reference ?

**Comment by spencergibb** [comment]
@eepstein http://projects.spring.io/spring-cloud/#release-trains

**Comment by spencergibb** [comment]
@user20161119 1.4.x is not compatible with Spring Boot 2. Please join us in gitter or stack overflow for questions

**Comment by Jamlee** [comment]
@spencergibb how to slove this problem   ????

**Comment by spencergibb** [comment]
Use compatible versions

**Comment by jianyuanzh** [comment]
Hi @spencergibb , thanks for your answers. But 1.4.4 is the latest version for spring cloud, does that mean we have no compatible spring cloud version for spring boot 2.0+?  And we have to use spring boot 1.5?

Thanks

**Comment by jianyuanzh** [comment]
I fixed this issue by using spring-boot 1.5.13.RELEASE with spring cloud 1.4.4.RELEASE.

**Comment by ryanjbaxter** [comment]
@jianyuanzh we dont recommend using version numbers for the spring cloud dependencies, you should be using the Spring Cloud BOM which manages the versions for you.  Our Finchley release train is compatible with Boot 2.0.x.  Our latest Finchley release is RC1 which is compatible with Boot 2.0.1.  Boot 2.0.2 is not compatible with Finchley.RC1, we will have another RC later next week that will be.

**Comment by kas-kad** [comment]
fixed it by aligning all spring-boot-test* dependencies versions with spring-boot-maven-plugin (made them having the same 2.0.2.RELEASE)

**Comment by zhilonglee** [comment]
Hi @ryanjbaxter, my problem has been solved. You explained it very well. Many thanks.

**Comment by swarnakumarp** [comment]
@ryanjbaxter Very well explained.
This certainly is meant for StackOverflow.

**Comment by FrancisKoya** [comment]
@spencergibb  Does spring-boot 2.2.4 version goes with Hoxton.SR1? if not which will be the ideal deal? Because I wanna use Netflix Hystrix.

**Comment by Ashishen** [comment]
Hi Guys,

I am trying to build a springboot camel application. I am required to work on the config maps using kubernetes.
I have added the following dependencies in my pom:
<dependency>
		    <groupId>io.fabric8</groupId>
		    <artifactId>spring-cloud-starter-kubernetes</artifactId>
		    <version>0.1.6</version>
		</dependency>
		<dependency>
		    <groupId>io.fabric8</groupId>
		    <artifactId>spring-cloud-kubernetes-core</artifactId>
		    <version>0.1.6</version>
		</dependency>

On building the the application if am getting the following errror : "Caused by: java.lang.NoSuchMethodError: org.springframework.boot.builder.SpringApplicationBuilder.<init>([Ljava/lang/Object;)V"

I have tried to add springboot cloud dependencies and tried to search for the compatibility, hence i added <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-dependencies</artifactId>
            <version>Greenwich.SR5</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
which is compatible with springboot 2.1.* version (mentioned in one of the forums).
I am still facing trouble with the build of the application.
Any leads are appreciated.

Thanks.

**Comment by rolzing** [comment]
I've changed this on my pom
```
<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.5.3.RELEASE</version>
		<relativePath/> 
	</parent>

<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.2.5.RELEASE</version>
	</parent>
```

We need to check our spring boot starter parent version.

**Comment by zhaoxi1988** [comment]
> @spencergibb Does spring-boot 2.2.4 version goes with Hoxton.SR1? if not which will be the ideal deal? Because I wanna use Netflix Hystrix.

+1 I have the same problem.

**Comment by gondaraju** [comment]
Hello all,
Actually we are working on migration of spring boot from 1.5.x version to 2.5.14 version once i have updated it to 2.5.14  and spring_cloud_version=2020.0.5 ,getting failed some test cases.can anyone help on this please.it is gradle project running on jdk 11.


java.lang.NoSuchMethodError: 'void org.springframework.boot.SpringApplication.<init>(java.lang.Object[])'
	at org.springframework.boot.test.context.SpringBootContextLoader.getSpringApplication(SpringBootContextLoader.java:131)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:94)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:98)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:116)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:83)
	at org.springframework.test.context.web.ServletTestExecutionListener.setUpRequestContextIfNecessary(ServletTestExecutionListener.java:189)
	at org.springframework.test.context.web.ServletTestExecutionListener.prepareTestInstance(ServletTestExecutionListener.java:131)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:230)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:228)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:287)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:289)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:247)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
