### ISSUE TITLE
InfoEndpoint not worked with spring-boot 1.4.0M2

### ISSUE THREAD

**Issue by wangxufire** [spring-cloud/spring-cloud-config#372]
```
Caused by: java.lang.NoSuchMethodError: org.springframework.boot.actuate.endpoint.InfoEndpoint.invoke()Ljava/util/Map;
	at org.springframework.cloud.autoconfigure.RefreshEndpointAutoConfiguration$InfoEndpointRebinderConfiguration.infoEndpoint(RefreshEndpointAutoConfiguration.java:162) ~[spring-cloud-context-1.1.0.RC1.jar:1.1.0.RC1]
	at org.springframework.cloud.autoconfigure.RefreshEndpointAutoConfiguration$InfoEndpointRebinderConfiguration.postProcessAfterInitialization(RefreshEndpointAutoConfiguration.java:150) ~[spring-cloud-context-1.1.0.RC1.jar:1.1.0.RC1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:422) ~[spring-beans-4.3.0.RC1.jar:4.3.0.RC1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1583) ~[spring-beans-4.3.0.RC1.jar:4.3.0.RC1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545) ~[spring-beans-4.3.0.RC1.jar:4.3.0.RC1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.3.0.RC1.jar:4.3.0.RC1]
```

**Comment by EXPEanlagnada** [comment]
What is the target version for the fix?

**Comment by spencergibb** [comment]
As far as I can tell this is no longer a problem with 1.4.1.RELEASE. If you can supply a project that recreates the problem feel free to share and I'll reopen.

**Comment by EXPEanlagnada** [comment]
I just tried 1.4.1 release spring boot and actuator and still failed.  Unfortunately it is an internal project.

![image](https://cloud.githubusercontent.com/assets/6675274/18770184/41ee8508-80e8-11e6-9016-9c6539d4d54f.png)

```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:506)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'infoEndpoint' defined in class path resource [org/springframework/boot/actuate/autoconfigure/EndpointAutoConfiguration.class]: Initialization of bean failed; nested exception is java.lang.NoSuchMethodError: org.springframework.boot.actuate.endpoint.InfoEndpoint.<init>(Ljava/util/Map;)V
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:775)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175)
	at com.sample.www.meta.pixel.trend.Application.main(Application.java:18)
	... 6 more
Caused by: java.lang.NoSuchMethodError: org.springframework.boot.actuate.endpoint.InfoEndpoint.<init>(Ljava/util/Map;)V
	at org.springframework.cloud.autoconfigure.RefreshEndpointAutoConfiguration$InfoEndpointRebinderConfiguration$1.<init>(RefreshEndpointAutoConfiguration.java:156)
	at org.springframework.cloud.autoconfigure.RefreshEndpointAutoConfiguration$InfoEndpointRebinderConfiguration.infoEndpoint(RefreshEndpointAutoConfiguration.java:156)
	at org.springframework.cloud.autoconfigure.RefreshEndpointAutoConfiguration$InfoEndpointRebinderConfiguration.postProcessAfterInitialization(RefreshEndpointAutoConfiguration.java:144)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:422)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1583)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	... 21 more
```

**Comment by spencergibb** [comment]
My guess is that you have mixed versions. What are your dependencies?

**Comment by EXPEanlagnada** [comment]
Hi Spencer,
I investigated further and found the issue.  The pom was referencing an older spring-cloud-context.  The following fixed the issue.

Thanks for prompt response.
```
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-context</artifactId>
            <version>1.1.3.RELEASE</version>
        </dependency>
```

**Comment by Luonero** [comment]
the same issue , hao 2 solve this proble?
